// Generated by R2O 1.0.Developped by Patrick Bashizi Mutuzi. All right reserved.

package pojos;


import com.pbash.r2o.dataAccess.DataObject;
import java.sql.*;
import java.util.ArrayList;


public class Cours extends DataObject{

private Integer idcours;
private String intitule;
private Integer ponderation;
private Integer titulaire;
}
