// Generated by R2O 1.0.Developped by Patrick Bashizi Mutuzi. All right reserved.

package pojos;


import com.pbash.r2o.dataAccess.DataObject;
import java.sql.*;
import java.util.ArrayList;


public class Epreuve extends DataObject{

private Integer idepreuve;
private Integer session;
private Integer idcours;
private Integer idetudiant;
private Double cote_annee;
private Double cote_examen;
}
