// Generated by R2O 1.0.Developped by Patrick Bashizi Mutuzi. All right reserved.

package pojos;


import com.pbash.r2o.dataAccess.DataObject;
import java.sql.*;
import java.util.ArrayList;


public class Etudiant extends DataObject{

private Integer idEtudiant;
private String nom;
private String postnom;
private String prenom;
private String password;
private String promotion;
}
