package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblEnvios generated by hbm2java
 */
public class TblEnvios  implements java.io.Serializable {


     private Integer envioCodigo;
     private TblFatura tblFatura;
     private TblPedidos tblPedidos;
     private String envioRastreio;
     private String envioData;
     private Set tblItensPedidos = new HashSet(0);




}


