package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblItensPedido generated by hbm2java
 */
public class TblItensPedido  implements java.io.Serializable {


     private Integer itensPedidoCodigo;
     private TblPedidoItemStatus tblPedidoItemStatus;
     private TblPedidos tblPedidos;
     private TblProduto tblProduto;
     private String itensPedidoQuantidade;
     private String itensPedidoPreco;
     private Set tblEnvioses = new HashSet(0);




}


