package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1



/**
 * TblMetodosPagamentoCliente generated by hbm2java
 */
public class TblMetodosPagamentoCliente  implements java.io.Serializable {


     private Integer metodosPagamentoClienteCodigo;
     private TblCliente tblCliente;
     private TblRefMetodosPagamento tblRefMetodosPagamento;
     private String refMetodosPagamentoCartaoCreditoNumero;
     private String refMetodosPagamentoDetalhes;




}


