package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblPedidos generated by hbm2java
 */
public class TblPedidos  implements java.io.Serializable {


     private Integer pedidoCodigo;
     private TblCliente tblCliente;
     private TblRefPedidoStatus tblRefPedidoStatus;
     private String pedidoDataPedidoFeito;
     private String pedidoDetalhes;
     private Set tblEnvioses = new HashSet(0);
     private Set tblItensPedidos = new HashSet(0);
     private Set tblFaturas = new HashSet(0);




}


