package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1



/**
 * TblPagamentos generated by hbm2java
 */
public class TblPagamentos  implements java.io.Serializable {


     private Integer pagamentosCodigo;
     private TblFatura tblFatura;
     private String pagamentosData;
     private String pagamentosQuantia;




}


