package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblPedidoItemStatus generated by hbm2java
 */
public class TblPedidoItemStatus  implements java.io.Serializable {


     private Integer pedidoItemStatusCodigo;
     private String pedidoItemDescricao;
     private Set tblItensPedidos = new HashSet(0);




}


