package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblRefTipoProduto generated by hbm2java
 */
public class TblRefTipoProduto  implements java.io.Serializable {


     private Integer refTipoProdutoCodigo;
     private TblRefTipoProduto tblRefTipoProduto;
     private String refTipoProdutoCategoriaProduto;
     private String refTipoProdutoDescricao;
     private Set tblProdutos = new HashSet(0);
     private Set tblRefTipoProdutos = new HashSet(0);




}


