package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblRefPedidoStatus generated by hbm2java
 */
public class TblRefPedidoStatus  implements java.io.Serializable {


     private Integer refPedidoStatusCodigo;
     private String refPedidoStatusDescricao;
     private Set tblPedidoses = new HashSet(0);




}


