package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblRefMetodosPagamento generated by hbm2java
 */
public class TblRefMetodosPagamento  implements java.io.Serializable {


     private Integer refMetodosPagamentoCodigo;
     private String refMetodosPagamentoDescricao;
     private Set tblMetodosPagamentoClientes = new HashSet(0);




}


