package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblRefFaturaStatus generated by hbm2java
 */
public class TblRefFaturaStatus  implements java.io.Serializable {


     private Integer refFaturaStatusCodigo;
     private String refFaturaStatusDescricao;
     private Set tblFaturas = new HashSet(0);




}


