

/** [ARG-V](https://arg-v.dev) was used to collect, filter, and transform these benchmarks automatically */
import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {
	/** ARG-V: suitable */
	 public static int demoMethod(int x, int y) {
		double var1 = Verifier.nondetDouble();
		double var2 = 10.0 * helperFunction(x, y);
		double result = var1 * var2;
		int z = x * y;
		if (result > z) {
			assert true; //inline assert generated by ARG-V
			return x;
		} else {
			assert true; //inline assert generated by ARG-V
			return y;
		}
	}
	
	/** ARG-V: suitable */
	 private static double helperFunction(int x, int y) {
		if (x > y) {
			assert true; //inline assert generated by ARG-V
			return Verifier.nondetDouble();
		} else {
			assert true; //inline assert generated by ARG-V
			return 10.0;
		}
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		demoMethod(Verifier.nondetInt(), Verifier.nondetInt());
		helperFunction(Verifier.nondetInt(), Verifier.nondetInt());
	}
}
