csv=dataset.csv
projectCount=200
maxLoc=10000
minLoc=100
downloadDir=database
benchmarkDir=benchmarks
debug=false
debugLevel=2
type=R
minExpr=1
minIfStmt=1
minParams=1
minTypeExpr=0
minTypeCond=0
minTypeParams=0
transformAll=true
simplifyFilter=true
target=SVCOMP
verifier=src/java/org/sosy_lab/sv_benchmarks/Verifier.java

