

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {
	/** ARG-V: suitable */
	 public static int baseTestCase(int x) {
		double[] a = new double[5];
		a[0] = Verifier.nondetDouble();
		if (x > a[0]) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else {
			assert true; //inline assert generated by ARG-V
			return 0;
		}
	}

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception {
		baseTestCase(Verifier.nondetInt(
	}
}
