

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {

  /** ARG-V: suitable */
 public int stringOperations(String data) {
    int count = 0;
    if (data.length() > 0) {
      count += data.indexOf("test");
      count += data.lastIndexOf("end");
      count += data.substring(0, 1).length();
      count += data.replace("a", "b").length();
      count += data.split(",").length;
      count += data.compareTo("other");
    }
    assert true; //inline assert generated by ARG-V
	return count;
  }

  /** ARG-V: suitable */
 public String variousConcatenations(String a, String b, String c) {
    String result1 = a + b;
    String result2 = result1 + c;
    String result3 = a + b + c;
    assert true; //inline assert generated by ARG-V
	return (result1 + result2 + result3).trim();
  }

  public boolean stringComparisons(String input) {
    if (input.equals("exact") && input.length() > 0) {
      assert true; //inline assert generated by ARG-V
	return true;
    }
    if (input.equalsIgnoreCase("ignore") && input.contains("test")) {
      assert true; //inline assert generated by ARG-V
	return true;
    }
    if (input.startsWith("pre") && input.endsWith("post")) {
      assert true; //inline assert generated by ARG-V
	return true;
    }
    assert true; //inline assert generated by ARG-V
	return false;
  }

  public String noStringOps(String data) {
    assert true; //inline assert generated by ARG-V
	return data.toString(); // Just returning, no operations
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.stringOperations(Verifier.nondetString());
	instance.variousConcatenations(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
	instance.stringComparisons(Verifier.nondetString());
	instance.noStringOps(Verifier.nondetString());
}
}
