

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {
    
    public static int testVar = 1;
    
	/** ARG-V: suitable */
	 public static int baseTestCase(int x) {
		if (x > testVar) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else {
			assert true; //inline assert generated by ARG-V
			return 0;
		}
	}

	/** This main was generated by ARG-V */
	 public static void main(String[] args) {
		baseTestCase(Verifier.nondetInt());
	}

}
