

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {

  /** ARG-V: suitable */
 public String emptyString(String input) {
    if (input.length() == 0) {
      assert true; //inline assert generated by ARG-V
	return "empty";
    }
    assert true; //inline assert generated by ARG-V
	return "not empty: " + input.length();
  }

  /** ARG-V: suitable */
 public String processStringArray(String[] inputs) {
    String result = "";
    assert true; //inline assert generated by ARG-V
	return result.endsWith(",") ? result.substring(0, result.length() - 1) : result;
  }

  public String returnNull(String input) {
    if (input == Verifier.nondetString()) {
      assert true; //inline assert generated by ARG-V
	return Verifier.nondetString(); // Should fail return type check
    }
    assert true; //inline assert generated by ARG-V
	return "not null";
  }

  /** ARG-V: suitable */
 public void voidStringOp(String data) {
    System.out.println(data.length()); // No meaningful operations
  }

  /** ARG-V: suitable */
 public char stringCharMethod(char c) {
    assert true; //inline assert generated by ARG-V
	return Character.toUpperCase(c);
  }

  /** ARG-V: suitable */
 public int processObject(Object obj) {
    assert true; //inline assert generated by ARG-V
	return obj.toString().length();
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.emptyString(Verifier.nondetString());
	instance.processStringArray(new java.lang.String[] { Verifier.nondetString() });
	instance.returnNull(Verifier.nondetString());
	instance.voidStringOp(Verifier.nondetString());
	instance.stringCharMethod(Verifier.nondetChar());
	instance.processObject((java.lang.Object) null);
}
}
