name: RealMail
description: Send mail to physical mailboxes without commands
version: 0.3.2
author: Ben Sergent V

main: com.challengercity.plugins.realmail.RealMail
database: false
#depend: [WorldEdit]

permissions:
  realmail.user.*:
    description: Access to personal mailboxes
    default: true
    children:
      realmail.user.sendmail: true
      realmail.user.attach: true
      realmail.user.craft.*:
        description: Access to crafting recipes
        default: true
        children:
          realmail.user.craft.mailbox: true
          realmail.user.craft.stationary: true
  realmail.admin.*:
    description: Access to commands like bulk-mailing
    default: op
    children:
      realmail.admin.bulkmail: true
      realmail.admin.sendmailAnywhere: true
      realmail.admin.openMailboxAnywhere: true
      realmail.admin.openMailboxAnywhere.others: true
      realmail.admin.bypassAttachmentLimits: true
      realmail.admin.instantDelivery: true
      realmail.admin.seeAdminHelp: true
      realmail.admin.spawn.*:
        description: Spawn items in
        default: op
        children:
          realmail.admin.spawn.mailbox: true
          realmail.admin.spawn.stationary: true
      
commands:
  realmail:
    description: Shows usage information for RealMail
    aliases: [mail, mailbox, rm]