

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {
	public int baseTestCase(int x) {
		int replaceTarget = Verifier.nondetInt() * 10;
		if (x > replaceTarget) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else {
			assert true; //inline assert generated by ARG-V
			return 0;
		}
	}

	public static void main(String[] args) {
		Main instance = new Main();
		instance.baseTestCase(Verifier.nondetInt());
	}

}
