

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {
	public static int splitter(double input1, double input2) {
		double value = (double) (Verifier.nondetDouble() * 10.0);
		double time = (double) System.nanoTime();
		if (value > input2) {
			assert true; //inline assert generated by ARG-V
			return -1;
		} else if (time > input1) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else {
			assert true; //inline assert generated by ARG-V
			return 0;
		}
	}
	
	public static void main(String[] args) {
		splitter(Verifier.nondetDouble(), Verifier.nondetDouble());
	}

}
