

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {

  /** ARG-V: suitable */
 public String processBuilder(StringBuilder input) {
    if (input.length() > 0) {
      assert true; //inline assert generated by ARG-V
	return input.append("suffix").toString();
    }
    assert true; //inline assert generated by ARG-V
	return input.toString();
  }

  /** ARG-V: suitable */
 public String processBuffer(StringBuffer buffer) {
    if (buffer.length() > 0) {
      assert true; //inline assert generated by ARG-V
	return buffer.toString().trim();
    }
    assert true; //inline assert generated by ARG-V
	return buffer.toString();
  }

  public StringBuilder createBuilder(String base) {
    assert true; //inline assert generated by ARG-V
	return new StringBuilder(base);
  }

  /** ARG-V: suitable */
 public StringBuilder mixedBuilder(StringBuilder sb, int count) {
    sb.append(count);
    assert true; //inline assert generated by ARG-V
	return new StringBuilder(sb.toString());
  }

  /** ARG-V: suitable */
 public void builderOperations(StringBuilder sb) {
    sb.append("test");
    sb.insert(0, "prefix");
    sb.reverse();
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.processBuilder(new StringBuilder(Verifier.nondetString()));
	instance.processBuffer(new StringBuffer(Verifier.nondetString()));
	instance.createBuilder(Verifier.nondetString());
	instance.mixedBuilder(new StringBuilder(Verifier.nondetString()), Verifier.nondetInt());
	instance.builderOperations(new StringBuilder(Verifier.nondetString()));
}
}
