

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {
	public static int baseTestCase(int x) {
		int[] a = new int[Verifier.nondetInt()];
		a[0] = 5;
		if (x > a[0]) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else {
			assert true; //inline assert generated by ARG-V
			return 0;
		}
	}

	public static void main(String[] args) {
		baseTestCase(Verifier.nondetInt());
	}
}
