package dungeonDigger.network;

public enum ConnectionState {
	IDLE, SINGLEPLAYER,
	LOGGINGON, CONNECTING, CONNECTED,
	LISTENING, SERVING,
	DISCONNECTED, 
	SETTINGUP, 
	LAUNCHINGGAME, HOSTINGGAME, 
	JOININGGAME, INGAME;
}
