

/** [ARG-V](https://arg-v.dev) was used to collect, filter, and transform these benchmarks automatically */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {
	/** ARG-V: suitable */
	 public static int splitter(float input1, float input2) {
		float value = (float) (Verifier.nondetFloat() * 10.0);
		float baseCase = Verifier.nondetFloat();
		float parenthesizedTime = ((float) System.nanoTime());
		if (value > input2) {
			assert true; //inline assert generated by ARG-V
			return -1;
		} else if (input2 > input1) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else {
			assert true; //inline assert generated by ARG-V
			return 0;
		}
	}
	
	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception {
		splitter(Verifier.nondetFloat(), Verifier.nondetFloat());
	}

}
