package cyd.awesome.material;

/**
 * Created by daniellevass on 02/04/15.
 */
public class FontCharacterMaps {


    public enum Pixeden {


        PE_ALBUM("\uE6AA"),
        PE_ARC("\uE6AB"),
        PE_BACK_2("\uE6AC"),
        PE_BANDAID("\uE6AD"),
        PE_CAR("\uE6AE"),
        PE_DIAMOND("\uE6AF"),
        PE_DOOR_LOCK("\uE6B0"),
        PE_EYEDROPPER("\uE6B1"),
        PE_FEMALE("\uE6B2"),
        PE_GYM("\uE6B3"),
        PE_HAMMER("\uE6B4"),
        PE_HEADPHONES("\uE6B5"),
        PE_HELM("\uE6B6"),
        PE_HOURGLASS("\uE6B7"),
        PE_LEAF("\uE6B8"),
        PE_MAGIC_WAND("\uE6B9"),
        PE_MALE("\uE6BA"),
        PE_MAP_2("\uE6BB"),
        PE_NEXT_2("\uE6BC"),
        PE_PAINT_BUCKET("\uE6BD"),
        PE_PENDRIVE("\uE6BE"),
        PE_PHOTO("\uE6BF"),
        PE_PIGGY("\uE6C0"),
        PE_PLUGIN("\uE6C1"),
        PE_REFRESH_2("\uE6C2"),
        PE_ROCKET("\uE6C3"),
        PE_SETTINGS("\uE6C4"),
        PE_SHIELD("\uE6C5"),
        PE_SMILE("\uE6C6"),
        PE_USB("\uE6C7"),
        PE_VECTOR("\uE6C8"),
        PE_WINE("\uE6C9"),
        PE_CLOUD_UPLOAD("\uE68A"),
        PE_CASH("\uE68C"),
        PE_CLOSE("\uE680"),
        PE_BLUETOOTH("\uE68D"),
        PE_CLOUD_DOWNLOAD("\uE68B"),
        PE_WAY("\uE68E"),
        PE_CLOSE_CIRCLE("\uE681"),
        PE_ID("\uE68F"),
        PE_ANGLE_UP("\uE682"),
        PE_WRISTWATCH("\uE690"),
        PE_ANGLE_UP_CIRCLE("\uE683"),
        PE_WORLD("\uE691"),
        PE_ANGLE_RIGHT("\uE684"),
        PE_VOLUME("\uE692"),
        PE_ANGLE_RIGHT_CIRCLE("\uE685"),
        PE_USERS("\uE693"),
        PE_ANGLE_LEFT("\uE686"),
        PE_USER_FEMALE("\uE694"),
        PE_ANGLE_LEFT_CIRCLE("\uE687"),
        PE_UP_ARROW("\uE695"),
        PE_ANGLE_DOWN("\uE688"),
        PE_SWITCH("\uE696"),
        PE_ANGLE_DOWN_CIRCLE("\uE689"),
        PE_SCISSORS("\uE697"),
        PE_WALLET("\uE600"),
        PE_SAFE("\uE698"),
        PE_VOLUME2("\uE601"),
        PE_VOLUME1("\uE602"),
        PE_VOICEMAIL("\uE603"),
        PE_VIDEO("\uE604"),
        PE_USER("\uE605"),
        PE_UPLOAD("\uE606"),
        PE_UNLOCK("\uE607"),
        PE_UMBRELLA("\uE608"),
        PE_TRASH("\uE609"),
        PE_TOOLS("\uE60A"),
        PE_TIMER("\uE60B"),
        PE_TICKET("\uE60C"),
        PE_TARGET("\uE60D"),
        PE_SUN("\uE60E"),
        PE_STUDY("\uE60F"),
        PE_STOPWATCH("\uE610"),
        PE_STAR("\uE611"),
        PE_SPEAKER("\uE612"),
        PE_SIGNAL("\uE613"),
        PE_SHUFFLE("\uE614"),
        PE_SHOPBAG("\uE615"),
        PE_SHARE("\uE616"),
        PE_SERVER("\uE617"),
        PE_SEARCH("\uE618"),
        PE_FILM("\uE6A5"),
        PE_SCIENCE("\uE619"),
        PE_DISK("\uE6A6"),
        PE_RIBBON("\uE61A"),
        PE_REPEAT("\uE61B"),
        PE_REFRESH("\uE61C"),
        PE_ADD_USER("\uE6A9"),
        PE_REFRESH_CLOuD("\uE61D"),
        PE_PAPERCLIP("\uE69C"),
        PE_RADIO("\uE61E"),
        PE_NOTE2("\uE69D"),
        PE_PRINT("\uE61F"),
        PE_NETWORK("\uE69E"),
        PE_PREV("\uE620"),
        PE_MUTE("\uE69F"),
        PE_POWER("\uE621"),
        PE_MEDAL("\uE6A0"),
        PE_PORTFOLIO("\uE622"),
        PE_LIKE2("\uE6A1"),
        PE_PLUS("\uE623"),
        PE_LEFT_ARROW("\uE6A2"),
        PE_PLAY("\uE624"),
        PE_KEY("\uE6A3"),
        PE_PLANE("\uE625"),
        PE_JOY("\uE6A4"),
        PE_PHOTO_GALLERY("\uE626"),
        PE_PIN("\uE69B"),
        PE_PHONE("\uE627"),
        PE_PLUG("\uE69A"),
        PE_PEN("\uE628"),
        PE_RIGHT_ARROW("\uE699"),
        PE_PAPER_PLANE("\uE629"),
        PE_DELETE_USER("\uE6A7"),
        PE_PAINT("\uE62A"),
        PE_BOTTOM_ARROW("\uE6A8"),
        PE_NOTEBOOK("\uE62B"),
        PE_NOTE("\uE62C"),
        PE_NEXT("\uE62D"),
        PE_NEWS_PAPER("\uE62E"),
        PE_MUSICLIST("\uE62F"),
        PE_MUSIC("\uE630"),
        PE_MOUSE("\uE631"),
        PE_MORE("\uE632"),
        PE_MOON("\uE633"),
        PE_MONITOR("\uE634"),
        PE_MICRO("\uE635"),
        PE_MENU("\uE636"),
        PE_MAP("\uE637"),
        PE_MAP_MARKER("\uE638"),
        PE_MAIL("\uE639"),
        PE_MAIL_OPEN("\uE63A"),
        PE_MAIL_OPEN_FILE("\uE63B"),
        PE_MAGNET("\uE63C"),
        PE_LOOP("\uE63D"),
        PE_LOOK("\uE63E"),
        PE_LOCK("\uE63F"),
        PE_LINTERN("\uE640"),
        PE_LINK("\uE641"),
        PE_LIKE("\uE642"),
        PE_LIGHT("\uE643"),
        PE_LESS("\uE644"),
        PE_KEYPAD("\uE645"),
        PE_JUNK("\uE646"),
        PE_INFO("\uE647"),
        PE_HOME("\uE648"),
        PE_HELP2("\uE649"),
        PE_HELP1("\uE64A"),
        PE_GRAPH3("\uE64B"),
        PE_GRAPH2("\uE64C"),
        PE_GRAPH1("\uE64D"),
        PE_GRAPH("\uE64E"),
        PE_GLOBAL("\uE64F"),
        PE_GLEAM("\uE650"),
        PE_GLASSES("\uE651"),
        PE_GIFT("\uE652"),
        PE_FOLDER("\uE653"),
        PE_FLAG("\uE654"),
        PE_FILTER("\uE655"),
        PE_FILE("\uE656"),
        PE_EXPAND1("\uE657"),
        PE_EXAPND2("\uE658"),
        PE_EDIT("\uE659"),
        PE_DROP("\uE65A"),
        PE_DRAWER("\uE65B"),
        PE_DOWNLOAD("\uE65C"),
        PE_DISPLAY2("\uE65D"),
        PE_DISPLAY1("\uE65E"),
        PE_DISKETTE("\uE65F"),
        PE_DATE("\uE660"),
        PE_CUP("\uE661"),
        PE_CULTURE("\uE662"),
        PE_CROP("\uE663"),
        PE_CREDIT("\uE664"),
        PE_COPY_FILE("\uE665"),
        PE_CONFIG("\uE666"),
        PE_COMPASS("\uE667"),
        PE_COMMENT("\uE668"),
        PE_COFFEE("\uE669"),
        PE_CLOUD("\uE66A"),
        PE_CLOCK("\uE66B"),
        PE_CHECK("\uE66C"),
        PE_CHAT("\uE66D"),
        PE_CART("\uE66E"),
        PE_CAMERA("\uE66F"),
        PE_CALL("\uE670"),
        PE_CALCULATOR("\uE671"),
        PE_BROWSER("\uE672"),
        PE_BOX2("\uE673"),
        PE_BOX1("\uE674"),
        PE_BOOKMARKS("\uE675"),
        PE_BICYCLE("\uE676"),
        PE_BELL("\uE677"),
        PE_BATTERY("\uE678"),
        PE_BALL("\uE679"),
        PE_BACK("\uE67A"),
        PE_ATTENTION("\uE67B"),
        PE_ANCHOR("\uE67C"),
        PE_ALBUMS("\uE67D"),
        PE_ALARM("\uE67E"),
        PE_AIRPLAY("\uE67F");


        private final String text;

        public enum FontAwesome {



        private final String text;

        public enum MaterialDesign {

        private final String text;


    }//end MaterialDesign enum


}
