

/** [ARG-V](https://arg-v.dev) was used to collect, filter, and transform these benchmarks automatically */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {
	/** ARG-V: suitable */
	 public static int variedTestCase(int x, int y, int z) {
		int v1 = (int) (Verifier.nondetInt() * 5);
		int v4 = (int) (Verifier.nondetInt() * 10) + y + Math.abs(5);
		if (x > v1) {
			assert true; //inline assert generated by ARG-V
			return helperFunctionOne(y);
		} else {
			assert true; //inline assert generated by ARG-V
			return helperFunctionOne(v4);
		}
	}
	
	/** ARG-V: suitable */
	 public static int helperFunctionOne(int a) {
		int v2 = (int) (Verifier.nondetInt() * 2);
		int v3 = (int) Math.random() / 1000;
		if (a > v2 && a > v3) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else if (a == v2 || a == v3) {
			assert true; //inline assert generated by ARG-V
			return 2;
		} else {
			assert true; //inline assert generated by ARG-V
			return a * 500;
		}
	}

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception {
		variedTestCase(Verifier.nondetInt(), Verifier.nondetInt(), Verifier.nondetInt());
		helperFunctionOne(Verifier.nondetInt());
	}

}
