

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {
	public static int splitter(int input1, int input2) {
		int value = (int) (Verifier.nondetInt() * 10);
		if (value > input2) {
			assert true; //inline assert generated by ARG-V
			return -1;
		} else if (input2 > input1) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else {
			assert true; //inline assert generated by ARG-V
			return 0;
		}
	}
	
	public static void main(String[] args) {
		splitter(Verifier.nondetInt(), Verifier.nondetInt());
	}

}
