package com.freelancersteam.www.java.tomafoto.dominio;
// Generated 22/07/2013 12:24:46 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia  implements java.io.Serializable {


     private Integer idAsistencia;
     private Empleado empleado;
     private String estado;
     private byte[] imagen;
     private Date fecha;
     private Date hora;
     private Boolean modificado;
     private Date fechaModificado;
     private Boolean correcto;
     private String observacion;
     private Boolean reajuste;




}


