package com.freelancersteam.www.java.tomafoto.dominio;
// Generated 22/07/2013 12:24:46 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private Integer cuit;
     private String denominacion;
     private String domicilio;
     private Date fechaInicio;
     private String ingresoBruto;
     private String categoria;
     private byte[] imagen;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);




}


