

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {

	static int MY_NUM = 5;
	static int[] c = new int[MY_NUM];
	static int d[] = new int[MY_NUM];

	/** ARG-V: suitable */
	 public static int baseTestCase(int x) {
		int[] a = new int[Verifier.nondetInt()];
		int b[] = new int[Verifier.nondetInt()];
		a[0] = 5;
		b[0] = 5;
		c[0] = 5;
		d[0] = 5;
		if (x > a[0]) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else {
			assert true; //inline assert generated by ARG-V
			return 0;
		}
	}

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception {
		baseTestCase(Verifier.nondetInt());
	}
}
