

/** [ARG-V](https://arg-v.dev) was used to collect, filter, and transform these benchmarks automatically */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {
    
    public static String testVar = "testString";
    
	/** ARG-V: suitable */
	 public static int baseTestCase(int x) {
		if (x > testVar.length()) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else {
			assert true; //inline assert generated by ARG-V
			return 0;
		}
	}

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception {
		baseTestCase(Verifier.nondetInt());
	}

}
