package transform.visitors;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import logging.Logger;
import org.eclipse.jdt.core.dom.*;
import org.eclipse.jdt.core.dom.rewrite.ASTRewrite;
import org.eclipse.jdt.core.dom.InfixExpression.Operator;

import sourceAnalysis.AnalyzedFile;
import sourceAnalysis.AnalyzedMethod;
import transform.TypeChecking.TypeChecker;
import transform.TypeChecking.TypeTable;
import transform.TypeChecking.TypeChecker.CType;
import util.ASTUtils;
import util.TypeResolutionUtils;

/**
 * The last visitor to be called. Two major tasks:
 * 1. Generates the main method that calls all of the methods that were found in
 * the AST.
 * 2. Obtains statistics about the number of expressions, operations in
 * expressions, conditions, and parameters. These are used for filtering and
 * analysis post-transformation.
 */
public class FinalizerVisitor extends ASTVisitor {

  private AnalyzedMethod currAnalyzedMethod;
  private AnalyzedFile af;

  private int minTypeExpr;
  private int minTypeCond;
  private int minTypeParams;
  private TypeTable typeTable;
  private CType type;
  private int operationsInExpression;
  private ASTRewrite rewriter;
  private AST ast;
  private TypeChecker typeChecker;

  private HashMap<String, Integer> currOpCounts = new HashMap<>();
  private static final Logger logger = Logger.defaultLogger;

  public FinalizerVisitor(AST ast, ASTRewrite rewriter, TypeChecker typeChecker, AnalyzedFile af, TypeTable typeTable,
      int minTypeExpr, int minTypeCond, int minTypeParams, CType type) {
    this.af = af;
    this.typeTable = typeTable;
    this.minTypeExpr = minTypeExpr;
    this.minTypeCond = minTypeCond;
    this.minTypeParams = minTypeParams;
    this.type = type;
    this.ast = ast;
    this.rewriter = rewriter;
    this.typeChecker = typeChecker;
    operationsInExpression = 0;
    // System.out.println("Done setting Finilizer Visitor");
  }

  @Override
  public boolean visit(TypeDeclaration node) {
    // System.out.println("Type " + node.getName());
    return true;
  }

  /**
   * Generates a new main method that invokes all of the suitable methods found in
   * the AST.
   * Escapes from our current symbolTable scope. Does not pop on interfaces
   * because we do not enter the scope of interfaces.
   */
  @Override
  public void endVisit(TypeDeclaration node) {
    // Detect our constructor
    MethodDeclaration constructor = null;
    for (Object memberObj : node.bodyDeclarations()) {
      if (memberObj instanceof MethodDeclaration) {
        MethodDeclaration methodDecl = (MethodDeclaration) memberObj;
        if (methodDecl.isConstructor()) {
          constructor = methodDecl;
        }
      }
    }

    // Create the main method declaration.
    if (node.getParent() instanceof CompilationUnit) {
      MethodDeclaration mainMethod = ast.newMethodDeclaration();
      mainMethod.setName(ast.newSimpleName("main"));
      mainMethod.modifiers().add(ast.newModifier(Modifier.ModifierKeyword.PUBLIC_KEYWORD));
      mainMethod.modifiers().add(ast.newModifier(Modifier.ModifierKeyword.STATIC_KEYWORD));
      mainMethod.thrownExceptionTypes().add(ast.newSimpleType(ast.newSimpleName("Exception")));
      mainMethod.setReturnType2(ast.newPrimitiveType(PrimitiveType.VOID));

      // Create the String[] args parameter.
      SingleVariableDeclaration param = ast.newSingleVariableDeclaration();
      ArrayType arrayType = ast.newArrayType(ast.newSimpleType(ast.newSimpleName("String")));
      param.setType(arrayType);
      param.setName(ast.newSimpleName("args"));
      mainMethod.parameters().add(param);

      Block mainBlock = ast.newBlock();
      mainMethod.setBody(mainBlock);

      // add comment above main method
      Statement commentPlaceholder = (Statement) rewriter
          .createStringPlaceholder("/** This main was generated by ARG-V */\n", ASTNode.EMPTY_STATEMENT);
      rewriter.getListRewrite(mainMethod, MethodDeclaration.MODIFIERS2_PROPERTY).insertFirst(commentPlaceholder, null);

      // Collect all methods to invoke (skip constructors and any existing main).
      boolean needsInstance = false;
      List<MethodDeclaration> methodDeclarations = new ArrayList<>();
      for (Object memberObj : node.bodyDeclarations()) {
        if (memberObj instanceof MethodDeclaration) {
          MethodDeclaration methodDecl = (MethodDeclaration) memberObj;
          if (!methodDecl.isConstructor() && !methodDecl.getName().getIdentifier().equals("main")) {
            methodDeclarations.add(methodDecl);
            // If any method is non-static, we will need an instance.
            if (!Modifier.isStatic(methodDecl.getModifiers())) {
              needsInstance = true;
            }
          }
        }
      }

      // If at least one non-static method exists, create an instance using the no-arg
      // constructor.
      if (needsInstance) {
        // Creates: ClassName instance = new ClassName();
        VariableDeclarationFragment fragment = ast.newVariableDeclarationFragment();
        fragment.setName(ast.newSimpleName("instance"));
        ClassInstanceCreation cic = ast.newClassInstanceCreation();
        if (constructor != null) {
          for (SingleVariableDeclaration paramObj : (List<SingleVariableDeclaration>) constructor.parameters()) {
            ITypeBinding normalizedType = ASTUtils.getNormalizedBinding(paramObj);
            Expression expr = TypeResolutionUtils.createSymbolicArgument(normalizedType, ast, false);
            if (expr instanceof NullLiteral && typeChecker.allowedType(normalizedType)) {
              Type newType = ASTUtils.newTypeFromBinding(ast, normalizedType);
              CastExpression cast = ast.newCastExpression();
              cast.setExpression((Expression) ASTNode.copySubtree(ast, expr));
              cast.setType(newType);
              cic.arguments().add(cast);
            } else {
              cic.arguments().add(expr);
            }
          }
        }
        cic.setType(ast.newSimpleType(ast.newSimpleName(node.getName().getIdentifier())));
        fragment.setInitializer(cic);

        VariableDeclarationStatement instanceDecl = ast.newVariableDeclarationStatement(fragment);
        instanceDecl.setType(ast.newSimpleType(ast.newSimpleName(node.getName().getIdentifier())));
        mainBlock.statements().add(instanceDecl);
      }

      // For each method, create a method invocation statement with symbolic
      // arguments.
      for (MethodDeclaration methodDecl : methodDeclarations) {
        MethodInvocation invocation = ast.newMethodInvocation();
        invocation.setName(ast.newSimpleName(methodDecl.getName().getIdentifier()));

        // If the method is non-static, invoke it on the instance.
        if (!Modifier.isStatic(methodDecl.getModifiers())) {
          invocation.setExpression(ast.newSimpleName("instance"));
        }

        // Process each parameter of the method.
        for (Object paramObj : methodDecl.parameters()) {
          if (paramObj instanceof SingleVariableDeclaration) {
            SingleVariableDeclaration svd = (SingleVariableDeclaration) paramObj;
            ITypeBinding normalizedType = ASTUtils.getNormalizedBinding(svd);
            Expression arg = TypeResolutionUtils.createSymbolicArgument(normalizedType, ast, false);
            if (arg instanceof NullLiteral && typeChecker.allowedType(normalizedType)) {
              Type newType = ASTUtils.newTypeFromBinding(ast, normalizedType);
              CastExpression cast = ast.newCastExpression();
              cast.setExpression((Expression) ASTNode.copySubtree(ast, arg));
              cast.setType(newType);
              invocation.arguments().add(cast);
            } else {
              invocation.arguments().add(arg);
            }
          }
        }

        ExpressionStatement invocationStmt = ast.newExpressionStatement(invocation);
        mainBlock.statements().add(invocationStmt);
      }

      // Insert the newly created main method into the class.
      rewriter.getListRewrite(node, TypeDeclaration.BODY_DECLARATIONS_PROPERTY)
          .insertLast(mainMethod, null);
    }
  }
  // Analysis logic from SuitableMethodFinder#AnalyzerVisitor

  @Override
  public boolean visit(FieldDeclaration node) {

    return false;
  }

  @Override
  public boolean visit(Initializer node) {
    return false;
  }

  @Override
  public boolean visit(NormalAnnotation node) {
    return false;
  }

  @Override
  public boolean visit(MarkerAnnotation node) {
    return false;
  }

  @Override
  public boolean visit(SingleMemberAnnotation node) {
    return false;
  }

  @Override
  public boolean visit(AnnotationTypeDeclaration node) {
    return false;
  }

  @Override
  public boolean visit(EnumDeclaration node) {
    return false;
  }

  @Override
  public boolean visit(MethodDeclaration node) {
    AnalyzedMethod am = new AnalyzedMethod(node);
    af.addMethod(am);

    checkParameterTypes(am, node);
    // currMethodDeclaration = node;
    currAnalyzedMethod = am;
    // System.out.println("Method\t" + am.getName());

    // @SuppressWarnings("unchecked")
    // HashSet<String> liveIntVariables = (HashSet<String>)
    // classIntVariables.clone();
    // @SuppressWarnings("unchecked")
    // List<SingleVariableDeclaration> parameters =
    // (List<SingleVariableDeclaration>) (node.parameters());
    //
    // for (SingleVariableDeclaration parameter : parameters) {
    // Type parameterType = parameter.getType();
    // if (!parameterType.isPrimitiveType())
    // continue;
    //
    // if (isIntegerTypeCode(parameterType)) {
    // String parameterName = parameter.getName().getIdentifier();
    // liveIntVariables.add(parameterName);
    // }
    // }
    //
    // blockStack.push(liveIntVariables);

    return true;
  }

  @Override
  public void endVisit(MethodDeclaration node) {
    // System.out.println("Visiting " + node.getName());
    AnalyzedMethod m = currAnalyzedMethod;
//    int intOpCount = m.getTypeOperationCount();
    // if (intOpCount > 0) {
    //   m.setHasTypeOperations(true);
    // }

    // if (m.getTypeConditionalCount() > 0) {
    //   m.setHasTypeConditional(true);
    // }

    if (m.getTypeParameterCount() > 0) {
      m.setHasOnlyTypeParameters(true);
    }

    if (m.getTypeConditionalCount() < minTypeCond ||
            m.getTypeOperationCount() < minTypeExpr ||
            m.getTypeParameterCount() < minTypeParams) {
      // System.out.println("Removing " + node.getName());
//      rewriter.remove(node, null);
    } else {
      af.addSuitableMethod(m);
    }

    // record operation information about method (derive class level etc. later)
    m.setOpCounts(currOpCounts);
    currOpCounts = new HashMap<>();
  }

  @Override
  public boolean visit(Block node) {
    // if (!blockStack.empty()) {
    // HashSet<String> liveIntVariables = blockStack.peek();
    // @SuppressWarnings("unchecked")
    // HashSet<String> localVarsClone = (HashSet<String>) liveIntVariables.clone();
    // blockStack.push(localVarsClone);
    // } else {
    // blockStack.push(new HashSet<>());
    // }
    return true;
  }

  // @Override
  // public void endVisit(Block node) {
  // blockStack.pop();
  // }

  @Override
  public boolean visit(IfStatement node) {
    // eas we need to check whether the expression is of int type
    // do we do it here or somewhere else?
    Expression e = node.getExpression();
    boolean hasType = hasType(e);
    // System.out.println(e.getClass() + " " + hasType + " " +
    // typeTable.getNodeType(e));
    // try to visit it and find out whether it has integer exprssions?
    // it can be 1) Boolean expression, 2) Infix expression, 3) Conditional
    // expression
    // other expressions that can return boolean value
    // let's focus on infix expressions
    // let's not -- just check whether the expression has required type
    // that is operands there have type for which analysis is built
    // -- if(e instanceof InfixExpression) {
    // InfixExpression infE = (InfixExpression) e;
    // Expression lE = infE.getLeftOperand();
    // Type t = typeTable.getNodeType(lE);
    // if(TypeChecker.checkType(t) == type) {
    // currAnalyzedMethod.setHasConditional(true);
    // }
    // remember the count before
    if (hasType) {
      currAnalyzedMethod.incrementTypeConditionalCount();
    }

    // --}

    // then the visitor will go into expression and count
    // what it needs to count
    return true;
  }

  // does any part of the expression have the specified type?
  private boolean hasType(Expression e) {
    if (e instanceof InfixExpression) {
      InfixExpression infE = (InfixExpression) e;
      return hasType(infE.getLeftOperand()) || hasType(infE.getRightOperand());
    } else if (e instanceof ConditionalExpression) {
      ConditionalExpression condE = (ConditionalExpression) e;
      return hasType(condE.getThenExpression()) || hasType(condE.getElseExpression());
    } else if (e instanceof MethodInvocation) {
      MethodInvocation mi = (MethodInvocation) e;
      Type recType = typeTable.getNodeType(mi.getExpression());
      if (type == CType.STRING && TypeChecker.isStringType(recType)) {
        return TypeChecker.isStringOp(mi.getName().getIdentifier());
      } else {
        return type.equals(TypeChecker.checkType(recType));
      }
    } else if (e instanceof ParenthesizedExpression) {
      return hasType(((ParenthesizedExpression) e).getExpression());
    } else if (e instanceof PrefixExpression) {
      return hasType(((PrefixExpression) e).getOperand());
    } else if (e instanceof PostfixExpression) {
      return hasType(((PostfixExpression) e).getOperand());
    } else if (e instanceof FieldAccess) {
      return type.equals(TypeChecker.checkType(typeTable.getNodeType(e)));
    } else if (e instanceof QualifiedName) {
      return type.equals(TypeChecker.checkType(typeTable.getNodeType(e)));
    } else if (e instanceof SimpleName) {
      return type.equals(TypeChecker.checkType(typeTable.getNodeType(e)));
    } else {
      // fallback: check the type of the expression
      return type.equals(TypeChecker.checkType(typeTable.getNodeType(e)));
    }
  }

  // for determining whether the expression for an if statement has relevant type
  // private boolean hasType(Expression e) {
  // boolean ret = false;
  // if (e instanceof InfixExpression) {
  // InfixExpression infE = (InfixExpression) e;
  // Expression lE = infE.getLeftOperand();
  // Expression rE = infE.getRightOperand();
  // return hasType(lE) || hasType(rE);
  // // Type lT = typeTable.getNodeType(lE);
  // // Type rT = typeTable.getNodeType(rE);
  // //
  // // if (TypeChecker.checkType(lT) == type || TypeChecker.checkType(rT) ==
  // type) {
  // // ret = true;
  // // } else if (TypeChecker.isBooleanType(rT) || TypeChecker.isBooleanType(lT))
  // {
  // // // call again since it might be just a complex expression
  // // ret = hasType(lE) || hasType(rE);
  // // }
  // //
  // // // Concatenation special case
  // // if (type == CType.STRING && infE.getOperator() ==
  // // InfixExpression.Operator.PLUS) {
  // // // either has to be (specifically) String for result to be String
  // // if (TypeChecker.isStringTypeSpecifically(lT) ||
  // // TypeChecker.isStringTypeSpecifically(rT)) {
  // // ret = true;
  // // }
  // // }
  // } else if (e instanceof MethodInvocation) {
  // MethodInvocation mi = (MethodInvocation) e;
  // String methodName = mi.getName().getIdentifier();
  // Type recType = typeTable.getNodeType(mi.getExpression());
  // if (type == CType.STRING && TypeChecker.isStringType(recType)) {
  // return TypeChecker.isStringOp(methodName);
  // } else {
  // return type.equals(TypeChecker.checkType(recType));
  // }
  // } else {
  // // if it is not an infix expression then it should
  // // be some single var of a boolean type
  // Type vT = typeTable.getNodeType(e);
  // // if (TypeChecker.isBooleanType(vT)) {
  // // System.out.println("Just a var");
  // // ret = true;
  // // }
  // return type.equals(TypeChecker.checkType(vT));
  // }
  // }

  @Override
  public void endVisit(IfStatement node) {
    // System.out.println("done visiting");
  }

  /*
   * What about while statement?
   */

  @Override
  public boolean visit(ForStatement node) {
    currAnalyzedMethod.setHasLoop(true);
    // To handle scope of local variables
    // if (!blockStack.empty()) {
    // HashSet<String> liveIntVariables = blockStack.peek();
    // @SuppressWarnings("unchecked")
    // HashSet<String> localVarsClone = (HashSet<String>) liveIntVariables.clone();
    // blockStack.push(localVarsClone);
    // } else {
    // blockStack.push(new HashSet<>());
    // }
    //
    // @SuppressWarnings("unchecked")
    // List<Expression> initializers = node.initializers();
    //
    // for (Expression variable : initializers) {
    // if (variable.getNodeType() != ASTNode.VARIABLE_DECLARATION_EXPRESSION)
    // continue;
    //
    // Type variableType = ((VariableDeclarationExpression) variable).getType();
    //
    // if (!variableType.isPrimitiveType())
    // continue;
    //
    // if (isIntegerTypeCode(variableType)) {
    // @SuppressWarnings("unchecked")
    // List<VariableDeclarationFragment> fragments =
    // ((VariableDeclarationExpression) variable)
    // .fragments();
    // HashSet<String> liveIntVariables = blockStack.pop();
    //
    // for (VariableDeclarationFragment fragment : fragments) {
    // String loopVariable = fragment.getName().getIdentifier();
    // liveIntVariables.add(loopVariable);
    // }
    //
    // blockStack.push(liveIntVariables);
    // }
    // }
    return true;
  }

  @Override
  public void endVisit(ForStatement node) {
    // blockStack.pop();
  }

  @Override
  public boolean visit(VariableDeclarationStatement node) {

    // Type variableType = node.getType();
    // if (!variableType.isPrimitiveType()) {
    // // right now we are just ignoring non-primitive declarations
    // return true;
    // }
    //
    // @SuppressWarnings("unchecked")
    // List<VariableDeclarationFragment> fragments = node.fragments();
    // HashSet<String> liveIntVariables = blockStack.pop();
    //
    // if (isIntegerTypeCode(variableType)) {
    // for (VariableDeclarationFragment fragment : fragments) {
    // String variableName = fragment.getName().getIdentifier();
    // liveIntVariables.add(variableName);
    // }
    //
    // } else {
    // // Check if we are redefining an instance variable to be non integer
    // for (VariableDeclarationFragment fragment : fragments) {
    // String variableName = fragment.getName().getIdentifier();
    //
    // if (isLiveIntVariable(variableName)) {
    // liveIntVariables.remove(variableName);
    // }
    // }
    // }
    //
    // blockStack.push(liveIntVariables);

    return true;
  }

  // @Override
  // public boolean visit(Assignment node) {
  // HashSet<String> liveIntVariables = blockStack.peek();
  // Expression lhs = node.getLeftHandSide();
  // if (!isVariable(lhs)) {
  // return true;
  // }
  // String variableName = lhs.toString();
  // if (liveIntVariables.contains(variableName)) {
  // if (node.getOperator() != Assignment.Operator.ASSIGN) {
  // currAnalyzedMethod.setIntOperationCount(currAnalyzedMethod.getIntOperationCount()+1);
  // }
  // }
  // return true;
  // }

  @Override
  public boolean visit(CastExpression node) {
    // expressionsStack.push(node);
    return true;
  }

  // @Override
  // public void endVisit(CastExpression node) {
  // Type type = node.getType();
  // intExpression = isIntegerTypeCode(type) ? true : false;
  // //expressionsStack.pop();
  // //not sure why are we counting casting as an operation
  // //if (parentExpression()) {
  // if (intExpression) {
  // currAnalyzedMethod.setIntOperationCount(currAnalyzedMethod.getIntOperationCount()+1);
  // }
  // operationsInExpression = 0;
  // intExpression = true;
  // //}
  // }

  @Override
  public boolean visit(InfixExpression node) {
    // expressionsStack.push(node);

    // System.out.println(" n " + node + "\t" + typeTable.getNodeType(node));
    Expression lE = node.getLeftOperand();
    Type lT = typeTable.getNodeType(lE);
    Expression rE = node.getRightOperand();
    Type rT = typeTable.getNodeType(rE);
    Operator op = node.getOperator();

    // if the parent node is not a boolean type (no logical connections)
    // and if lhs and rhs of the required type than its op should some
    // kind of numerical operator

    if (type == CType.STRING && op == Operator.PLUS) {
      // special case of string concatenation
      if (TypeChecker.isStringTypeSpecifically(lT) || TypeChecker.isStringTypeSpecifically(rT)) {
        currOpCounts.merge("concat", 1, Integer::sum);
        currAnalyzedMethod.incrementTypeOperationCount();
      }
      //check for additional concats
      List<Expression> extendedOperands = node.extendedOperands();
      if (extendedOperands != null && !extendedOperands.isEmpty()) {
        // we can just assume
        int numOps = extendedOperands.size();
        currOpCounts.merge("concat", numOps, Integer::sum);
        for (int i = 0; i < numOps; i++){
          currAnalyzedMethod.incrementTypeOperationCount();
        }
      }
      // causes String == null to incrementTypeOperationCount
    } else if ((TypeChecker.checkType(lT) == type || TypeChecker.checkType(rT) == type)) {

      // does it matter what type of operand is it?
      // if (op == Operator.PLUS ||
      // op == Operator.MINUS ||
      // op == Operator.DIVIDE ||
      // op == Operator.TIMES ||
      // op == Operator.REMAINDER) {
      // so we count that operations
      // if the type is int
      // if (!TypeChecker.isBooleanType(typeTable.getNodeType(node))) {
      // System.out.println("op " + op);
      currAnalyzedMethod.incrementTypeOperationCount();
      // }
      // }
    }
    // no need to go further if lhs is not of int type and not boolean
    // since a condition might use logical constructs to build complex expressions
    return !TypeChecker.isBooleanType(lT) && !TypeChecker.isBooleanType(rT);
  }

  @Override
  public boolean visit(MethodInvocation node) {
    if (type == CType.STRING) {
      String methodName = node.getName().getIdentifier();
      if (TypeChecker.isStringOp(methodName)) {
        currOpCounts.merge(methodName, 1, Integer::sum);
        currAnalyzedMethod.incrementTypeOperationCount();
        // operationsInExpression++;
      }
    }
    return true;
  }

  @Override
  public void endVisit(InfixExpression node) {
    // expressionsStack.pop();
    // if (operationsInExpression > 0) {
    // currAnalyzedMethod.setTypeOperationCount(currAnalyzedMethod.getTypeOperationCount()
    // + 1);
    // operationsInExpression = 0;
    // }
  }

  @Override
  public boolean visit(PrefixExpression node) {
    // expressionsStack.push(node);
    // System.out.println("Prefix " + node);
    Expression operand = node.getOperand();
    CType tOp = TypeChecker.checkType(typeTable.getNodeType(operand));
    if (tOp == type) {
      // so it is integer
      // operationsInExpression++;
      currAnalyzedMethod.incrementTypeOperationCount();
      // System.out.println("preixCount");
    } else {
      // no need to go if it is not an int
      return false;
    }

    return true;
  }

  @Override
  public void endVisit(PrefixExpression node) {
    // expressionsStack.pop();
    // if (operationsInExpression > 0) {
    // currAnalyzedMethod.setTypeOperationCount(currAnalyzedMethod.getTypeOperationCount()
    // + operationsInExpression);
    // operationsInExpression = 0;
    // }

  }

  @Override
  public boolean visit(PostfixExpression node) {
    // expressionsStack.push(node);
    // HashSet<String> liveIntVariables = blockStack.peek();
    Expression operand = node.getOperand();
    // System.out.println("postfix " + node);
    CType tOp = TypeChecker.checkType(typeTable.getNodeType(operand));
    if (tOp == type) {
      currAnalyzedMethod.incrementTypeOperationCount();
      // operationsInExpression++;
      // System.out.println("postfix");
    } else {
      // no need to go in if it is not an int
      return false;
    }

    return true;
  }

  @Override
  public void endVisit(PostfixExpression node) {
    // expressionsStack.pop();
    // if (operationsInExpression > 0) {
    // currAnalyzedMethod.setTypeOperationCount(currAnalyzedMethod.getTypeOperationCount()
    // + operationsInExpression);
    // operationsInExpression = 0;
    // }

  }

  private void checkParameterTypes(AnalyzedMethod am, MethodDeclaration node) {
    List<SingleVariableDeclaration> parameters = node.parameters();
    if (!parameters.isEmpty()) {
      // am.setHasParameters(true);
      int typeParams = 0;
      for (SingleVariableDeclaration parameter : parameters) {
        CType parType = TypeChecker.checkType(typeTable.getNodeType(parameter));
        if (parType == type) {
          typeParams++;
        }
      }
      // found all parameters of a particular type
      am.setTypeParameterCount(typeParams);
      if (parameters.size() == typeParams) {
        am.setHasOnlyTypeParameters(true);
      }

      // if (hasOnlyIntegerParameters(parameters)) {
      // am.setHasOnlyIntParameters(true);
      // am.setIntParameterCount(parameters.size());
      // } else {
      // am.setHasOnlyIntParameters(false);
      // }
    } else {
      // am.setHasParameters(false);
    }
  }
  // old finaliser analysis code, above is from SuitableMethodFinder#AnalyzerVisitor


  // public boolean hasOnlyIntegerParameters(List<SingleVariableDeclaration>
  // parameters) {
  // for (SingleVariableDeclaration parameter : parameters) {
  // CType parType = TypeChecker.checkType(typeTable.getNodeType(parameter));
  // if(parType != type && parType != CType.BOOLEAN) {
  // //if (!isIntegerParameter(parameter)) {
  // return false;
  // }
  // }
  // return true;
  // }

  // private boolean isSingleParameter(SingleVariableDeclaration parameter) {
  // return (parameter.getExtraDimensions() == 0 && !parameter.isVarargs());
  // }

  // private boolean isIntegerParameter(SingleVariableDeclaration parameter) {
  // if (!isSingleParameter(parameter))
  // return false;
  // Type type = parameter.getType();
  // if (!type.isPrimitiveType())
  // return false;
  //
  // Code typeCode = ((PrimitiveType) type).getPrimitiveTypeCode();
  // return (typeCode == PrimitiveType.CHAR || typeCode == PrimitiveType.INT ||
  // typeCode == PrimitiveType.LONG
  // || typeCode == PrimitiveType.SHORT || typeCode == PrimitiveType.BYTE);
  // }

  // private boolean isIntegerTypeCode(Type type) {
  // if (!type.isPrimitiveType())
  // return false;
  // Code typeCode = ((PrimitiveType) type).getPrimitiveTypeCode();
  //
  // return (typeCode == PrimitiveType.CHAR || typeCode == PrimitiveType.INT ||
  // typeCode == PrimitiveType.LONG
  // || typeCode == PrimitiveType.SHORT || typeCode == PrimitiveType.BYTE);
  // }
  //
  // private boolean isVariable(Expression exp) {
  // return (exp instanceof SimpleName || exp instanceof QualifiedName);
  // }

  // private boolean isLiveIntVariable(String name) {
  // HashSet<String> liveIntVariables = blockStack.peek();
  // if (liveIntVariables.contains(name)) {
  // return true;
  // }
  // return false;
  // }

  // private boolean parentExpression() {
  // return expressionsStack.isEmpty();
  // }
}
//  @Override
//  public boolean visit(FieldDeclaration node) {
//    return false; // do not analyze characteristics in field declarations
//  }
//
//  @Override
//  public boolean visit(MethodDeclaration node) {
//    AnalyzedMethod am = new AnalyzedMethod(node);
//    af.addMethod(am);
//
//    checkParameterTypes(am, node);
//    currAnalyzedMethod = am;
//
//    return true;
//  }
//
//  @Override
//  public void endVisit(MethodDeclaration node) {
//    // System.out.println("Visiting " + node.getName());
//    AnalyzedMethod m = currAnalyzedMethod;
//    int intOpCount = m.getTypeOperationCount();
//    // if (intOpCount > 0) {
//    //   m.setHasTypeOperations(true);
//    // }
//    //
//    // if (m.getTypeConditionalCount() > 0) {
//    //   m.setHasTypeConditional(true);
//    // }
//
//    if (m.getTypeParameterCount() > 0) {
//      m.setHasOnlyTypeParameters(true);
//    }
//    System.out.println("Oper " + m.getTypeOperationCount());
//    System.out.println("Cond " + m.getTypeConditionalCount());
//    System.out.println("Par " + m.getTypeParameterCount());
//
//    if (m.getTypeConditionalCount() < minTypeCond ||
//        m.getTypeOperationCount() < minTypeExpr ||
//        m.getTypeParameterCount() < minTypeParams) {
//      System.out.println("Commenting out " + node.getName());
//
//    } else {
//      af.addSuitableMethod(m);
//      System.out.println("Suitable method " + node.getName());
//    }
//
//  }
//
//  @Override
//  public boolean visit(Block node) {
//    // if (!blockStack.empty()) {
//    // HashSet<String> liveIntVariables = blockStack.peek();
//    // @SuppressWarnings("unchecked")
//    // HashSet<String> localVarsClone = (HashSet<String>) liveIntVariables.clone();
//    // blockStack.push(localVarsClone);
//    // } else {
//    // blockStack.push(new HashSet<>());
//    // }
//    return true;
//  }
//
//  // @Override
//  // public void endVisit(Block node) {
//  // blockStack.pop();
//  // }
//
//  @Override
//  public boolean visit(IfStatement node) {
//    // eas we need to check whether the expression is of int type
//    // do we do it here or somewhere else?
//    Expression e = node.getExpression();
//    boolean hasType = hasType(e);
//    // System.out.println(e.getClass() + " " + hasType + " " +
//    // typeTable.getNodeType(e));
//    // try to visit it and find out whether it has integer exprssions?
//    // it can be 1) Boolean expression, 2) Infix expression, 3) Conditional
//    // expression
//    // other expressions that can return boolean value
//    // let's focus on infix expressions
//    // let's not -- just check whether the expression has required type
//    // that is operands there have type for which analysis is built
//    // -- if(e instanceof InfixExpression) {
//    // InfixExpression infE = (InfixExpression) e;
//    // Expression lE = infE.getLeftOperand();
//    // Type t = typeTable.getNodeType(lE);
//    // if(TypeChecker.checkType(t) == type) {
//    // currAnalyzedMethod.setHasConditional(true);
//    // }
//    // remember the count before
//    if (hasType) {
//      currAnalyzedMethod.setTypeConditionalCount(currAnalyzedMethod.getTypeConditionalCount() + 1);
//
//    }
//
//    // --}
//
//    // then the visitor will go into expression and count
//    // what it needs to count
//    return true;
//  }
//
//  private boolean hasType(Expression e) {
//    boolean ret = false;
//    if (e instanceof InfixExpression) {
//      InfixExpression infE = (InfixExpression) e;
//      Expression lE = infE.getLeftOperand();
//      Expression rE = infE.getRightOperand();
//      Type lT = typeTable.getNodeType(lE);
//      Type rT = typeTable.getNodeType(rE);
//      if (TypeChecker.checkType(lT) == type || TypeChecker.checkType(rT) == type) {
//        ret = true;
//      } else if (TypeChecker.isBooleanType(rT) || TypeChecker.isBooleanType(lT)) {
//        // call again since it might be just a complex expression
//        ret = hasType(lE) || hasType(rE);
//      }
//    } else {
//      // if it is not an infix expression then it should
//      // be some single var of a boolean type
//      Type vT = typeTable.getNodeType(e);
//      if (TypeChecker.isBooleanType(vT)) {
//        // System.out.println("Just a var");
//        ret = true;
//      }
//    }
//    return ret;
//  }
//
//  @Override
//  public boolean visit(ForStatement node) {
//    currAnalyzedMethod.setHasLoop(true);
//    // To handle scope of local variables
//    return true;
//  }
//
//  @Override
//  public boolean visit(InfixExpression node) {
//    // expressionsStack.push(node);
//
//    // System.out.println(" n " + node + "\t" + typeTable.getNodeType(node));
//    Expression lE = node.getLeftOperand();
//    Type lT = typeTable.getNodeType(lE);
//    Expression rE = node.getRightOperand();
//    Type rT = typeTable.getNodeType(rE);
//    // if the parent node is not a boolean type (no logical connections)
//    // and if lhs and rhs of the required type than its op should some
//    // kind of numerical operator
//    if ((TypeChecker.checkType(lT) == type || TypeChecker.checkType(rT) == type)) {
//
//      // does it matter what type of operand is it?
//      Operator op = node.getOperator();
//      // if (op == Operator.PLUS ||
//      // op == Operator.MINUS ||
//      // op == Operator.DIVIDE ||
//      // op == Operator.TIMES ||
//      // op == Operator.REMAINDER) {
//      // so we count that operations
//      // if the type is int
//      // System.out.println(typeTable.getNodeType(node) +"\t" + lT + "\t" + rT);
//      Type nodeType = typeTable.getNodeType(node);
//      if (!TypeChecker.isBooleanType(nodeType)) {
//        // System.out.println("op " + op);
//        operationsInExpression++;
//      }
//      // }
//    } else if (!TypeChecker.isBooleanType(lT) && !TypeChecker.isBooleanType(rT)) {
//      // no need to go further if lhs is not of int type and not boolean
//      // since a condition might use logical constructs to build complex expressions
//      return false;
//    }
//    return true;
//  }
//
//  @Override
//  public void endVisit(InfixExpression node) {
//    // expressionsStack.pop();
//    if (operationsInExpression > 0 && currAnalyzedMethod != null) {
//      // why do we just add one? need to add all of them
//      // currAnalyzedMethod.setTypeOperationCount(currAnalyzedMethod.getTypeOperationCount()+1);
//      currAnalyzedMethod.setTypeOperationCount(currAnalyzedMethod.getTypeOperationCount() +
//          operationsInExpression);
//      operationsInExpression = 0;
//    }
//  }
//
//  @Override
//  public boolean visit(PrefixExpression node) {
//    // expressionsStack.push(node);
//    // System.out.println("Prefix " + node);
//    Expression operand = node.getOperand();
//    CType tOp = TypeChecker.checkType(typeTable.getNodeType(operand));
//    if (tOp == type) {
//      // so it is integer
//      operationsInExpression++;
//      // System.out.println("preixCount");
//    } else {
//      // no need to go if it is not an int
//      return false;
//    }
//
//    return true;
//  }
//
//  @Override
//  public void endVisit(PrefixExpression node) {
//    // expressionsStack.pop();
//    if (operationsInExpression > 0) {
//      currAnalyzedMethod.setTypeOperationCount(currAnalyzedMethod.getTypeOperationCount() + operationsInExpression);
//      operationsInExpression = 0;
//    }
//
//  }
//
//  @Override
//  public boolean visit(PostfixExpression node) {
//    // expressionsStack.push(node);
//    // HashSet<String> liveIntVariables = blockStack.peek();
//    Expression operand = node.getOperand();
//    // System.out.println("postfix " + node);
//    CType tOp = TypeChecker.checkType(typeTable.getNodeType(operand));
//    if (tOp == type) {
//      operationsInExpression++;
//      // System.out.println("postfix");
//    } else {
//      // no need to go in if it is not an int
//      return false;
//    }
//
//    return true;
//  }
//
//  @Override
//  public void endVisit(PostfixExpression node) {
//    // expressionsStack.pop();
//    if (operationsInExpression > 0) {
//      currAnalyzedMethod.setTypeOperationCount(currAnalyzedMethod.getTypeOperationCount() + operationsInExpression);
//      operationsInExpression = 0;
//    }
//
//  }
//
//  private void checkParameterTypes(AnalyzedMethod am, MethodDeclaration node) {
//    List<SingleVariableDeclaration> parameters = node.parameters();
//    if (!parameters.isEmpty()) {
//      // am.setHasParameters(true);
//      int typeParams = 0;
//      for (SingleVariableDeclaration parameter : parameters) {
//        CType parType = TypeChecker.checkType(typeTable.getNodeType(parameter));
//        if (parType == type) {
//          typeParams++;
//        }
//      }
//      // found all parameters of a particular type
//      am.setTypeParameterCount(typeParams);
//      if (parameters.size() == typeParams) {
//        am.setHasOnlyTypeParameters(true);
//      }
//
//      // if (hasOnlyIntegerParameters(parameters)) {
//      // am.setHasOnlyIntParameters(true);
//      // am.setIntParameterCount(parameters.size());
//      // } else {
//      // am.setHasOnlyIntParameters(false);
//      // }
//    } else {
//      // am.setHasParameters(false);
//    }
//  }
