// CSE 143, Homework 4: Tag
// Instructor-provided testing program.

import java.io.*;
import java.util.*;

/**
 * Class TagMain is the main client program for assassin game management.
 * It reads names from a file names.txt, shuffles them, and uses them to
 * start the game.  The user is asked for the name of the next victim until
 * the game is over.
 */
public class TagMain {
    /** input file name from which to read data */
    public static final String INPUT_FILENAME = "names.txt";
    
    /** true for different results every run; false for predictable results */
    public static final boolean RANDOM = false;
    
    /**
     * If not random, use this value to guide the sequence of numbers
     * that will be generated by the Random object.
     */
    public static final int SEED = 42;
}
