

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {



    /** 2. if-statement with empty then and non-empty else (should invert condition + move else) */
    /** ARG-V: suitable */
	 public void ifEmptyThenElse() {
    	int a = 1;
    	int b = 2;
        if (!(a > b)) {
			b = 3;
		}
    }

    /** 3. if-statement with non-empty then and empty else (should remove else) */
    /** ARG-V: suitable */
	 public void ifNonEmptyThenEmptyElse() {
    	int a = 1;
    	int b = 2;
        if (a > b) {
            a = 3;
        }
    }

    /** 4. while-loop with empty body (should become an EmptyStatement) */
    /** ARG-V: suitable */
	 public void whileEmptyBlock() {
    	int a = 1;
    	int b = 2;
    }


	 

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.ifEmptyThenElse();
		instance.ifNonEmptyThenEmptyElse();
		instance.whileEmptyBlock();
	}
}
