

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
 public class Main {

  /** ARG-V: suitable */
 public String stringReturn(String input) {
    assert true; //inline assert generated by ARG-V
	return input.trim().toUpperCase();
  }

  /** ARG-V: suitable */
 public void voidStringMethod(String data) {
    if (data != Verifier.nondetString()) {
      String processed = data.replace("old", "new");
      System.out.println(processed.length());
    }
  }

  /** ARG-V: suitable */
 public int nonStringReturn(String input) {
    assert true; //inline assert generated by ARG-V
	return input.length(); // int return, not string
  }

  /** ARG-V: suitable */
 public int mixedReturn(String input, int multiplier) {
    assert true; //inline assert generated by ARG-V
	return input.length() * multiplier;
  }

  public StringBuilder builderReturn(String base) {
    assert true; //inline assert generated by ARG-V
	return new StringBuilder(base);
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.stringReturn(Verifier.nondetString());
	instance.voidStringMethod(Verifier.nondetString());
	instance.nonStringReturn(Verifier.nondetString());
	instance.mixedReturn(Verifier.nondetString(), Verifier.nondetInt());
	instance.builderReturn(Verifier.nondetString());
}
}
