/** [ARG-V](https://arg-v.dev) was used to collect, filter, and transform these benchmarks automatically */

/*
 * Headers above the package 1
 * header2 2
 */
// header using single line 3
// another header using single line 4
/*
 * Headers below the package 5
 * header2 6
 */
// header with single line 7
// another header 8
// in-between import 9
/*
 * block between import 10
 */
// another comment 11
// java.util should be kept 12
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.Collections;

/*
 * Headers below the import 13
 */

// another header 14/14

/**
 * This class is a copy of SymbolicIntTest with comments added in.
 * This is a multiline JavaDoc Comment on the class
 * @author Charles Moloney
 */
/** filtered by ARG-V */
 public class Main {
	/**
	 * This is a JavaDoc Comment on a method
	 * @param input1 an integer
	 * @param input2 another integer
	 * @return something nonsensical from our if statements
	 */
	/** ARG-V: suitable */
	 public static int splitter(int input1, int input2) {
		int value = (int) (Verifier.nondetInt() * 10);
		/* This is a single line block comment */
		// This is a single line comment
		/*
		 * This is a multi-line block comment
		 * Second line
		 */
		if (value > input2) {
			assert true; //inline assert generated by ARG-V
			return -1;
		} else if (input2 > input1) {
			assert true; //inline assert generated by ARG-V
			return 1;
		} else {
			assert true; //inline assert generated by ARG-V
			return 0;
		}
	}
	
	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception {
		splitter(Verifier.nondetInt(), Verifier.nondetInt());
	}
}

// end of file comments
/*
 * More end of file comments
 * more end of file commments
 */
