name: Build and Test

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: oracle
      - name: Setup Gradle
        uses: actions/setup-gradle@v4
        with:
          gradle-version: "8.11.1"
      - name: Build and Test with Gradle
        run: |
          gradle clean
          gradle build
          gradle run
          gradle transform
          gradle reset

  build-and-test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: oracle
      - name: Setup Gradle
        uses: actions/setup-gradle@v4
        with:
          gradle-version: "8.11.1"
      - name: Build and Test with Gradle
        run: |
          gradle clean
          gradle build
          gradle run
          gradle transform
          gradle reset

  build-and-test-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: oracle
      - name: Setup Gradle
        uses: actions/setup-gradle@v4
        with:
          gradle-version: "8.11.1"
      - name: Build and Test with Gradle
        run: |
          gradle clean
          gradle build
          gradle run
          gradle transform
          gradle reset
