name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test-on-all-OS:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
      - name: Set Up App
        run: |
          ./gradlew
          ./gradlew clean
          ./gradlew build
      - name: Compile
        run: ./gradlew compile
      - name: Run
        run: |
          ./gradlew run
          ./gradlew transform
      - name: Clean Up
        run: ./gradlew reset
