name: Build and Test

on:
  pull_request:
    branches: [master develop]

jobs:
  build-and-test:
    runs-on: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
      - name: Build and Test with Gradle
        run: |
          gradle clean build run transform reset
