# Config used by docs/tutorial/README.md.
csv=dataset.csv
projectCount=1
maxLoc=10000
minLoc=1
downloadDir=database
benchmarkDir=benchmarks
debug=false
debugLevel=2
type=I
minExpr=1
minIfStmt=1
minParams=1
minTypeExpr=1
minTypeCond=1
minTypeParams=1
transformAll=true
simplifyFilter=false
target=SVCOMP
